export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
  TEACHER_NOT_FOUND: 'ERR_TEACHER_NOT_FOUND',
  TEACHER_HAS_GROUPS: 'ERR_TEACHER_HAS_GROUPS',
  GROUP_NOT_FOUND: 'ERR_GROUP_NOT_FOUND',
  GROUP_HAS_DEPENDENTS: 'ERR_GROUP_HAS_DEPENDENTS',
  STUDENT_NOT_FOUND: 'ERR_STUDENT_NOT_FOUND',
  TASK_NOT_FOUND: 'ERR_TASK_NOT_FOUND',
  SUBJECT_NOT_FOUND: 'ERR_SUBJECT_NOT_FOUND',
  SUBMISSION_NOT_FOUND: 'ERR_SUBMISSION_NOT_FOUND',
  SUBMISSION_ALREADY_COMPLETED: 'ERR_SUBMISSION_ALREADY_COMPLETED',
  TASK_HAS_SUBMISSIONS: 'ERR_TASK_HAS_SUBMISSIONS',
  FORBIDDEN_RESOURCE: 'ERR_FORBIDDEN_RESOURCE',
  VALIDATION_FAILED: 'ERR_VALIDATION_FAILED',
  USERNAME_TAKEN: 'ERR_USERNAME_TAKEN',
  INTERNAL_ERROR: 'ERR_INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
